### ISSUE TITLE
useTimeout - unnecessary dependency array

### ISSUE THREAD

**Issue by isBatak** [WebDevSimplified/useful-custom-react-hooks#8]
In the useTimeout hook you actually don't need a dependency array at all. Callback Function will be unstable on every render and trigger the side effect, so there is no point of doing [Object.is()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is) checks if you know it will return false. This is the best use-case for useEffect without dependency array. 
```
useEffect(() => {
    callbackRef.current = callback
});
```
https://github.com/WebDevSimplified/useful-custom-react-hooks/blob/f5dda2e69d51e5da52aa75f21c6e83610def5923/src/2-useTimeout/useTimeout.js#L9

**Comment by WebDevSimplified** [comment]
The reason I included a dependency array here is because some people may want to pass in a function that never changes, such as a useCallback function, and then we wouldn't need to update the callback unnecessarily. I think it doesn't really matter if you have the dependencies or not since either way one approach will be slightly less efficient based on how it is implemented.

**Comment by isBatak** [comment]
In this case wrapping the callback function in useCallback is even less performant because you have two dependency arrays, one for useCallback and another for useEffect. Also, assigning value on each pass seems more performant than comparing two values, but this is just my intuition. It could be a cool thing to profile…

**Comment by WebDevSimplified** [comment]
Good point. That is probably an improvement I could make but the performance implications are pretty minimal most likely.
